---
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: monitoring
  labels:
    dashboards: "grafana"
spec:
  config:
    security:
      admin_user: admin
      admin_password: admin
    server:
      root_url: "%(protocol)s://%(domain)s/"
  ingress:
    metadata:
      annotations:
        kubernetes.io/ingress.class: "traefik"
    spec:
      rules:
        - host: "grafana.local"
