---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: logs-analyzer-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: logs-analyzer-role
subjects:
  - kind: ServiceAccount
    name: logs-analyzer
    namespace: logs-analyzer
